package be.cytomine.appstore.dto.responses.errors;

public enum ErrorCode {
    /**
     * See ErrorDefinitions for code and message definitions
     */
    INTERNAL_DESCRIPTOR_EXTRACTION_FAILED,
    INTERNAL_DESCRIPTOR_NOT_IN_DEFAULT_LOCATION,
    INTERNAL_DOCKER_IMAGE_EXTRACTION_FAILED,
    INTERNAL_DOCKER_IMAGE_MANIFEST_MISSING,
    INTERNAL_DOCKER_IMAGE_TAR_NOT_FOUND,
    INTERNAL_MULTIPLE_ERRORS,
    INTERNAL_SCHEMA_VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    INTERNAL_TASK_EXISTS,
    INTERNAL_TASK_NOT_FOUND,
    INTERNAL_UNKNOWN_BUNDLE_ARCHIVE_FORAMT,
    STORAGE_CREATING_STORAGE_FAILED,
    INTERNAL_MISSING_OUTPUT_FILE_FOR_PARAMETER,
    INTERNAL_OUTPUT_FILE_FOR_PARAMETER_IS_DIRECTORY,
    INTERNAL_EXTRA_OUTPUT_FILES_FOR_PARAMETER,
    INTERNAL_OUTPUT_FILE_FOR_PARAMETER_IS_BLANK,
    INTERNAL_MISSING_METADATA,
    INTERNAL_INVALID_FEATURE_COLLECTION,
    INTERNAL_INVALID_COLLECTION_DIMENSIONS,
    INTERNAL_UNKNOWN_PARAMETER,
    INTERNAL_UNKNOWN_SUBTYPE,
    REGISTRY_PUSHING_TASK_IMAGE_FAILED,
    INTERNAL_PARAMETER_SCHEMA_VALIDATION_ERROR,
    INTERNAL_UNKNOWN_IMAGE_ARCHIVE_FORMAT,
    INTERNAL_MAX_UPLOAD_SIZE_EXCEEDED,
    INTERNAL_INVALID_BUNDLE_FORMAT,
    STORAGE_STORING_TASK_DEFINITION_FAILED,
    INTERNAL_INVALID_METADATA,
    INTERNAL_EMPTY_SEARCH_QUERY;
}
